/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
GRANT SELECT ON siac.siac_v_dwh_codice_bollo TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_cofog TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_conto_tesoreria TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_distinta TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_ente_proprietario TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mis_pro TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_accert_classe TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_accert_sogg TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_accertamento TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_impegno TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_impegno_classe TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_mod_impegno_sogg TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_pdc TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_relazione_doc TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_sac TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_stato_liquidazione TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tipo_accredito TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tipo_commissione TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tipo_documento TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tipo_finanziamento TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tipo_fondo TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tit_mac TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_tit_tip_cat TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_variazione_bilancio TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_ricevuta_ordinativo TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_anagrafica_classi_sog TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_relazione_classi_sog TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_anagrafica_mdp TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_provvisori_cassa TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_provvisori_cassa_ord TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_provvisori_cassa_subdoc TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_relazione_ordinativi TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_anag_progetti TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_vincoli_movgest TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_causali_econpatr TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_atto_amministrativo TO siac_dwh;
GRANT SELECT ON siac.siac_v_dwh_pcc TO siac_dwh;
GRANT SELECT ON siac_v_dwh_predocumenti_pagamento TO siac_dwh;
GRANT SELECT ON siac_v_dwh_mod_imp_sogg_classe TO siac_dwh;
GRANT SELECT ON siac_v_dwh_oneri_split TO siac_dwh;
GRANT SELECT ON siac_v_dwh_registrazioni TO siac_dwh;
GRANT SELECT ON siac_v_dwh_subdoc_sospensione TO siac_dwh;
GRANT SELECT ON siac_v_dwh_fattura_sirfel TO siac_dwh; 
GRANT SELECT ON siac_v_dwh_allegato_atto_flux TO siac_dwh; 
