/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
﻿-- 10.11.2017 Sofia SIOPE PLUS
-- DDL creazione e adeguamento struttura dati
-- da rilasciare in all.sql

CREATE TABLE mif_t_giornalecassa (
  mif_t_giornalecassa_id SERIAL,
  flusso_elab_mif_id INTEGER,
  codice_abi_bt VARCHAR,
  identificativo_flusso VARCHAR,
  data_ora_creazione_flusso VARCHAR,
  data_inizio_periodo_riferimento VARCHAR,
  data_fine_periodo_riferimento VARCHAR,
  codice_ente VARCHAR,
  descrizione_ente VARCHAR,
  codice_ente_bt VARCHAR,
  esercizio INTEGER,
  conto_evidenza VARCHAR,
  descrizione_conto_evidenza VARCHAR,
  tipo_movimento VARCHAR,
  tipo_documento VARCHAR,
  tipo_operazione VARCHAR,
  numero_documento INTEGER,
  progressivo_documento INTEGER,
  importo VARCHAR,
  numero_bolletta_quietanza INTEGER,
  numero_bolletta_quietanza_storno INTEGER,
  data_movimento VARCHAR,
  data_valuta_ente VARCHAR,
  tipo_esecuzione VARCHAR,
  coordinate VARCHAR,
  codice_riferimento_operazione VARCHAR,
  codice_riferimento_interno VARCHAR,
  tipo_contabilita VARCHAR,
  destinazione VARCHAR,
  assoggettamento_bollo VARCHAR,
  importo_bollo VARCHAR,
  assoggettamento_spese VARCHAR,
  importo_spese VARCHAR,
  anagrafica_cliente VARCHAR,
  indirizzo_cliente VARCHAR,
  cap_cliente VARCHAR,
  localita_cliente VARCHAR,
  codice_fiscale_cliente VARCHAR,
  provincia_cliente VARCHAR,
  partita_iva_cliente VARCHAR,
  anagrafica_delegato VARCHAR,
  indirizzo_delegato VARCHAR,
  cap_delegato VARCHAR,
  localita_delegato VARCHAR,
  provincia_delegato VARCHAR,
  codice_fiscale_delegato VARCHAR,
  causale VARCHAR,
  numero_sospeso INTEGER,
  validita_inizio TIMESTAMP WITHOUT TIME ZONE,
  validita_fine TIMESTAMP WITHOUT TIME ZONE,
  data_creazione TIMESTAMP WITHOUT TIME ZONE,
  data_cancellazione TIMESTAMP WITHOUT TIME ZONE,
  login_operazione VARCHAR(200),
  ente_proprietario_id INTEGER,
  assoggettamento_commissioni VARCHAR
)
WITH (oids = false);

CREATE TABLE mif_t_elab_giornalecassa
(
  mif_t_elab_giornalecassa_id SERIAL,
  mif_t_giornalecassa_id integer,
  flusso_elab_mif_id INTEGER,
  codice_abi_bt VARCHAR,
  identificativo_flusso VARCHAR,
  data_ora_creazione_flusso VARCHAR,
  data_inizio_periodo_riferimento VARCHAR,
  data_fine_periodo_riferimento VARCHAR,
  codice_ente VARCHAR,
  descrizione_ente VARCHAR,
  codice_ente_bt VARCHAR,
  esercizio INTEGER,
  conto_evidenza VARCHAR,
  descrizione_conto_evidenza VARCHAR,
  tipo_movimento VARCHAR,
  tipo_documento VARCHAR,
  tipo_operazione VARCHAR,
  numero_documento INTEGER,
  progressivo_documento INTEGER,
  importo NUMERIC,
  numero_bolletta_quietanza INTEGER,
  numero_bolletta_quietanza_storno INTEGER,
  data_movimento VARCHAR,
  data_valuta_ente VARCHAR,
  tipo_esecuzione VARCHAR,
  coordinate VARCHAR,
  codice_riferimento_operazione VARCHAR,
  codice_riferimento_interno VARCHAR,
  tipo_contabilita VARCHAR,
  destinazione VARCHAR,
  assoggettamento_bollo VARCHAR,
  importo_bollo NUMERIC,
  assoggettamento_spese VARCHAR,
  importo_spese NUMERIC,
  anagrafica_cliente VARCHAR,
  indirizzo_cliente VARCHAR,
  cap_cliente VARCHAR,
  localita_cliente VARCHAR,
  codice_fiscale_cliente VARCHAR,
  provincia_cliente VARCHAR,
  partita_iva_cliente VARCHAR,
  anagrafica_delegato VARCHAR,
  indirizzo_delegato VARCHAR,
  cap_delegato VARCHAR,
  localita_delegato VARCHAR,
  provincia_delegato VARCHAR,
  codice_fiscale_delegato VARCHAR,
  causale VARCHAR,
  numero_sospeso INTEGER,
  validita_inizio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  validita_fine TIMESTAMP WITHOUT TIME ZONE,
  data_creazione TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  data_cancellazione TIMESTAMP WITHOUT TIME ZONE,
  login_operazione VARCHAR(200) NOT NULL,
  ente_proprietario_id INTEGER
)
WITH (oids = false);

alter table mif_t_oil_ricevuta
 add oil_qualificatore_id integer,
 add oil_esito_derivato_id integer;

alter table siac_t_ente_oil
 add ente_oil_codice_opi varchar(50);

 CREATE TABLE siac.mif_t_giornalecassa_totali (
  mif_t_giornalecassa_totali_id SERIAL,
  flusso_elab_mif_id INTEGER,
  codice_abi_bt VARCHAR,
  identificativo_flusso VARCHAR,
  data_ora_creazione_flusso VARCHAR,
  data_inizio_periodo_riferimento VARCHAR,
  data_fine_periodo_riferimento VARCHAR,
  codice_ente VARCHAR,
  descrizione_ente VARCHAR,
  codice_ente_bt VARCHAR,
  esercizio INTEGER,
  saldo_complessivo_finale NUMERIC,
  saldo_complessivo_precedente NUMERIC,
  totale_complessivo_entrate NUMERIC,
  totale_complessivo_uscite NUMERIC,
  anticipazione_accordata NUMERIC,
  anticipazione_utilizzata NUMERIC,
  disponibilita NUMERIC,
  saldo_conti_bi NUMERIC,
  saldo_conti_correnti NUMERIC,
  svincoli_conti_bi NUMERIC,
  svincoli_conti_correnti NUMERIC,
  totale_conti NUMERIC,
  totale_somme_bloccate_riservate NUMERIC,
  totale_svincoli NUMERIC,
  totale_vincoli NUMERIC,
  vincoli_conti_bi NUMERIC,
  vincoli_conti_correnti NUMERIC,
  deficit_di_cassa NUMERIC,
  fondo_di_cassa NUMERIC,
  saldo_esercizio NUMERIC,
  totale_entrate NUMERIC,
  totale_mandati_pagati NUMERIC,
  totale_reversali_riscosse NUMERIC,
  totale_sospesi_entrata NUMERIC,
  totale_sospesi_uscita NUMERIC,
  totale_uscite NUMERIC,
  validita_inizio TIMESTAMP WITHOUT TIME ZONE,
  validita_fine TIMESTAMP WITHOUT TIME ZONE,
  data_creazione TIMESTAMP WITHOUT TIME ZONE,
  data_cancellazione TIMESTAMP WITHOUT TIME ZONE,
  login_operazione VARCHAR(200),
  ente_proprietario_id INTEGER
)
WITH (oids = false);