/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
CREATE OR REPLACE FUNCTION fnc_siac_bko_config_report_BILR129_xbrl()
  RETURNS character varying AS
$BODY$
DECLARE
  rec_enti	record;
  sMsgReturn	varchar(1000):='';
  nIdEnte	integer;
BEGIN
    sMsgReturn:='';
    for rec_enti in
      select A.ente_proprietario_id, A.ente_denominazione, D.eptipo_code
      from siac_t_ente_proprietario A, siac_r_ente_proprietario_tipo T, siac_d_ente_proprietario_tipo D
      where A.ente_proprietario_id = T.ente_proprietario_id
        and T.eptipo_id = D.eptipo_id
      order by A.ente_proprietario_id  
    loop
      nIdEnte:=rec_enti.ente_proprietario_id;

      DELETE FROM siac.siac_t_xbrl_mapping_fatti WHERE xbrl_mapfat_rep_codice='BILR129.tmap' AND ente_proprietario_id=nIdEnte;
      DELETE FROM siac.siac_t_xbrl_mapping_fatti WHERE xbrl_mapfat_rep_codice='BILR129' AND ente_proprietario_id=nIdEnte;
      DELETE FROM siac.siac_t_xbrl_report WHERE xbrl_rep_codice = 'BILR129' AND ente_proprietario_id=nIdEnte;

      INSERT INTO siac.siac_t_xbrl_report (xbrl_rep_codice,  xbrl_rep_fase_code,  xbrl_rep_tipologia_code,  xbrl_rep_xsd_tassonomia,  validita_inizio,  ente_proprietario_id,  login_operazione) VALUES ('BILR129','REND','SDB','bdap-sdb-rend-enti_2017-09-29.xsd',now(),nIdEnte,'admin');

      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','ImportoCodice','${cb_xbrl_tagname}','','i_anno/anno_bilancio*0/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','ImportoCodiceAnnoPrec','${cb_xbrl_tagname}','','i_anno/anno_bilancio*-1/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','TotImpABCDE','SP_Passivo','','i_anno/anno_bilancio*0/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','TotImpABCDEAnno-1','SP_Passivo','','i_anno/anno_bilancio*-1/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','TotImpAnno','${cb_xbrl_totimp_tagname}','','i_anno/anno_bilancio*-0/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129','TotImpAnno-1','${cb_xbrl_totimp_tagname}','','i_anno/anno_bilancio*-1/','eur','2', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','instant');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','0','SP_ContiOrdine','abstract','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','1','SP_ContiOrdineImpegniEserciziFuturi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','2','SP_ContiOrdineBeniTerziInUso','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','3','SP_ContiOrdineBeniDatiUsoTerzi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','4','SP_ContiOrdineGaranziePrestatePA','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','5','SP_ContiOrdineGaranziePrestateImpreseControllate','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','6','SP_ContiOrdineGaranziePrestateImpresePartecipate','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','7','SP_ContiOrdineGaranziePrestateAltreImprese','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A','SP_PatrimonioNetto','abstract','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.I','SP_PatrimonioNettoFondoDotazione','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II','SP_PatrimonioNettoRiserve','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II.a','SP_PatrimonioNettoRiserveEserciziPrec','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II.b','SP_PatrimonioNettoRiserveCapitale','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II.c','SP_PatrimonioNettoRiservePermessiCostruire','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.III','SP_PatrimonioNettoRisultatoEconomicoEsercizio','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','B','SP_FondiRischiOneri','abstract','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','B.1','SP_FondiRischiOneriTrattamentoQuiescenza','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','B.2','SP_FondiRischiOneriImposte','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','B.3','SP_FondiRischiOneriAltri','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','C','SP_TrattamentoFineRapporto','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D','SP_Debiti','abstract','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.1','SP_DebitiFinanz','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.1.a','SP_DebitiFinanzPrestitiObbligazionari','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.1.b','SP_DebitiFinanzVsAltrePA','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.1.c','SP_DebitiFinanzVsBancheTesorerie','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.1.d','SP_DebitiFinanzVsAltriFinanziatori','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.2','SP_DebitiVsFornitori','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.3','SP_DebitiAcconti','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4','SP_DebitiTrafContr','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4.a','SP_DebitiTrafContrEntiSSN','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4.b','SP_DebitiTrafContrAltrePA','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4.c','SP_DebitiTrafContrImpreseControllate','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4.d','SP_DebitiTrafContrImpresePartecipate','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.4.e','SP_DebitiTrafContrAltriSoggetti','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.5','SP_DebitiAltriDebiti','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.5.a','SP_DebitiAltriDebitiTributari','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.5.b','SP_DebitiAltriDebitiVsIstitutiPrevidenza','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.5.c','SP_DebitiAltriDebitiAttivitaCTerzi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','D.5.d','SP_DebitiAltriDebitiAltri','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E','SP_RateiRiscontiPassivo','abstract','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.I','SP_RateiRiscontiRateiPassivi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II','SP_RateiRiscontiRiscontiPassivi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II.1','SP_RateiRiscontiContrInvest','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II.1.a','SP_RateiRiscontiContrInvestAltrePA','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II.1.b','SP_RateiRiscontiContrInvestAltriSoggetti','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II.2','SP_RateiRiscontiConnessioniPluriennali','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','E.II.3','SP_RateiRiscontiAltriRiscontiPassivi','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II.d','SP_PatrimonioNettoRiserveIndBeniDemaPatriIndBeniCul','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
      INSERT INTO siac.siac_t_xbrl_mapping_fatti (xbrl_mapfat_rep_codice, xbrl_mapfat_variabile, xbrl_mapfat_fatto, xbrl_mapfat_tupla_group_key, xbrl_mapfat_periodo_code, xbrl_mapfat_unit_code, xbrl_mapfat_decimali, validita_inizio, ente_proprietario_id, login_operazione, xbrl_mapfat_periodo_tipo) VALUES ('BILR129.tmap','A.II.e','SP_PatrimonioNettoAltreRiserveIndisponibili','','unused','','0', to_timestamp('01-01-2016 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),nIdEnte,'admin','duration');
    end loop;

    return sMsgReturn;

exception
	when others THEN
		raise notice 'Errore di configurazione' ;
		sMsgReturn:='Errore di configurazione';
		return sMsgReturn;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION fnc_siac_bko_config_report_BILR129_xbrl()
  OWNER TO siac;
GRANT EXECUTE ON FUNCTION fnc_siac_bko_config_report_BILR129_xbrl() TO public;
GRANT EXECUTE ON FUNCTION fnc_siac_bko_config_report_BILR129_xbrl() TO siac;
GRANT EXECUTE ON FUNCTION fnc_siac_bko_config_report_BILR124_xbrl() TO siac_rw;
