/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
CREATE TABLE siac.tracciato_770_quadro_c (
  c_id SERIAL,
  elab_id INTEGER NOT NULL,
  elab_id_det INTEGER NOT NULL,
  elab_data TIMESTAMP WITHOUT TIME ZONE,
  ente_proprietario_id INTEGER,
  tipo_record VARCHAR(2),
  codice_fiscale_ente VARCHAR(16),
  codice_fiscale_percipiente VARCHAR(16),
  tipo_percipiente VARCHAR(1),
  cognome_denominazione VARCHAR(24),
  nome VARCHAR(20),
  sesso VARCHAR(1),
  data_nascita VARCHAR(8),
  comune_nascita VARCHAR(21),
  provincia_nascita VARCHAR(2),
  colonna_1 VARCHAR(21),
  colonna_2 VARCHAR(2),
  comune_domicilio_fiscale_prec VARCHAR(4),
  comune_domicilio_spedizione VARCHAR(21),
  provincia_domicilio_spedizione VARCHAR(2),
  colonna_3 VARCHAR(3),
  esclusione_precompilata VARCHAR(1),
  categorie_particolari VARCHAR(2),
  indirizzo_domicilio_spedizione VARCHAR(35),
  cap_domicilio_spedizione VARCHAR(5),
  colonna_4 VARCHAR(57),
  codice_sede VARCHAR(3),
  comune_domicilio_fiscale VARCHAR(4),
  rappresentante_codice_fiscale VARCHAR(16),
  percipienti_esteri_no_res VARCHAR(1),
  percipienti_esteri_localita VARCHAR(35),
  percipienti_esteri_stato VARCHAR(3),
  percipienti_esteri_cod_fiscale VARCHAR(20),
  ex_causale VARCHAR(1),
  ammontare_lordo_corrisposto VARCHAR(11),
  somme_no_ritenute_regime_conv VARCHAR(11),
  altre_somme_no_ritenute VARCHAR(11),
  imponibile_b VARCHAR(11),
  ritenute_titolo_acconto_b VARCHAR(11),
  ritenute_titolo_imposta_b VARCHAR(11),
  ritenute_sospese_b VARCHAR(11),
  anticipazione VARCHAR(1),
  anno VARCHAR(4),
  add_reg_titolo_acconto_b VARCHAR(11),
  add_reg_titolo_imposta_b VARCHAR(11),
  add_reg_sospesa_b VARCHAR(11),
  imponibile_anni_prec VARCHAR(11),
  ritenute_operate_anni_prec VARCHAR(11),
  contr_prev_carico_sog_erogante VARCHAR(11),
  contr_prev_carico_sog_percipie VARCHAR(11),
  spese_rimborsate VARCHAR(11),
  ritenute_rimborsate VARCHAR(11),
  colonna_5 VARCHAR(2),
  percipienti_esteri_via_numciv VARCHAR(35),
  colonna_6 VARCHAR(1),
  eventi_eccezionali VARCHAR(1),
  somme_prima_data_fallimento VARCHAR(11),
  somme_curatore_commissario VARCHAR(11),
  colonna_7 VARCHAR(11),
  colonna_8 VARCHAR(1),
  codice VARCHAR(1),
  colonna_9 VARCHAR(9),
  codice_fiscale_e VARCHAR(16),
  imponibile_e VARCHAR(11),
  ritenute_titolo_acconto_e VARCHAR(11),
  ritenute_titolo_imposta_e VARCHAR(11),
  ritenute_sospese_e VARCHAR(11),
  add_reg_titolo_acconto_e VARCHAR(11),
  add_reg_titolo_imposta_e VARCHAR(11),
  add_reg_sospesa_e VARCHAR(11),
  add_com_titolo_acconto_e VARCHAR(11),
  add_com_titolo_imposta_e VARCHAR(11),
  add_com_sospesa_e VARCHAR(11),
  add_com_titolo_acconto_b VARCHAR(11),
  add_com_titolo_imposta_b VARCHAR(11),
  add_com_sospesa_b VARCHAR(11),
  colonna_10 VARCHAR(103),
  codice_fiscale_redd_diversi_f VARCHAR(16),
  codice_fiscale_pignoramento_f VARCHAR(16),
  codice_fiscale_esproprio_f VARCHAR(16),
  colonna_11 VARCHAR(16),
  colonna_12 VARCHAR(1),
  colonna_13 VARCHAR(2),
  colonna_14 VARCHAR(4),
  colonna_15 VARCHAR(4),
  colonna_16 VARCHAR(4),
  colonna_17 VARCHAR(7),
  colonna_18 VARCHAR(6),
  colonna_19 VARCHAR(4),
  colonna_20 VARCHAR(7),
  colonna_21 VARCHAR(4),
  colonna_22 VARCHAR(9),
  colonna_23 VARCHAR(1),
  codice_fiscale_ente_prev VARCHAR(16),
  denominazione_ente_prev VARCHAR(30),
  codice_ente_prev VARCHAR(1),
  codice_azienda VARCHAR(15),
  categoria VARCHAR(1),
  altri_contributi VARCHAR(1),
  importo_altri_contributi VARCHAR(11),
  contributi_dovuti VARCHAR(11),
  contributi_versati VARCHAR(11),
  causale VARCHAR(2),
  colonna_24 VARCHAR(1044),
  colonna_25 VARCHAR(4),
  colonna_26 VARCHAR(4),
  colonna_27 VARCHAR(1818),
  anno_competenza VARCHAR(4),
  ex_ente VARCHAR(4),
  progressivo VARCHAR(7),
  matricola VARCHAR(7),
  codice_tributo VARCHAR(4),
  versione_tracciato_procsi VARCHAR(3),
  colonna_28 VARCHAR(9),
  caratteri_controllo_1 VARCHAR(1),
  caratteri_controllo_2 VARCHAR(2),
  CONSTRAINT tracciato_770_quadro_c_pkey PRIMARY KEY(c_id)
) 
WITH (oids = false);

CREATE UNIQUE INDEX tracciato_770_quadro_c_idx ON siac.tracciato_770_quadro_c
  USING btree (elab_id, elab_id_det);